-- Create profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  nom text,
  prenom text,
  email text,
  date_naissance date,
  etablissement_origine text,

  constraint nom_length check (char_length(nom) >= 2),
  constraint prenom_length check (char_length(prenom) >= 2)
);

-- Create notes table
create table notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  niveau text not null,
  etablissement text not null,
  matiere text not null,
  note numeric(4, 2) not null,

  constraint note_range check (note >= 0 and note <= 20)
);

-- Create voeux table
create table voeux (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  formation text not null,
  etablissement text not null,
  ville text,
  priorite int default 1
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table profiles enable row level security;
alter table notes enable row level security;
alter table voeux enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Policies for notes
create policy "Users can view their own notes." on notes
  for select using (auth.uid() = user_id);

create policy "Users can insert their own notes." on notes
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own notes." on notes
  for update using (auth.uid() = user_id);

create policy "Users can delete their own notes." on notes
  for delete using (auth.uid() = user_id);

-- Policies for voeux
create policy "Users can view their own voeux." on voeux
  for select using (auth.uid() = user_id);

create policy "Users can insert their own voeux." on voeux
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own voeux." on voeux
  for update using (auth.uid() = user_id);

create policy "Users can delete their own voeux." on voeux
  for delete using (auth.uid() = user_id);
